# .github/workflows/update_movies.yml
name: Update Movies JSON

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y gzip
          pip install pandas

      - name: Download IMDb datasets
        run: |
          curl -O https://datasets.imdbws.com/title.basics.tsv.gz
          curl -O https://datasets.imdbws.com/title.ratings.tsv.gz

      - name: Extract datasets
        run: |
          gunzip title.basics.tsv.gz
          gunzip title.ratings.tsv.gz

      - name: Run data processing script
        run: python data_processing.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/movies.json
          git commit -m 'Update movies.json with latest IMDb data' || echo 'No changes to commit'
          git push
